package com.homeautomationapp

object AppConstants {
    const val TAG_FRAGMENT_HEATERS = "TAG_FRAGMENT_HEATERS"
    const val TAG_FRAGMENT_LIGHTS = "TAG_FRAGMENT_LIGHTS"
    const val TAG_FRAGMENT_ROLLER_SHUTTERS = "TAG_FRAGMENT_ROLLER_SHUTTERS"
    const val TAG_FRAGMENT_USER_PROFILE = "TAG_FRAGMENT_USER_PROFILE"
    const val TAG_FRAGMENT_DEVICES_MANAGER = "TAG_FRAGMENT_DEVICES_MANAGER"
    const val TAG_DIALOG_CANCELLATION = "TAG_DIALOG_CANCELLATION"
    const val TAG_DIALOG_RESET = "TAG_DIALOG_RESET"
    const val TAG_DIALOG_FILTER = "TAG_DIALOG_FILTER"
    const val TAG_DIALOG_DELETE = "TAG_DIALOG_DELETE"
}